update: dockerfile from node:16.17.1-buster
palladium-tms/palladium-view pull request #430
Opened 2024-03-26 15:12 UTC by askonev

[node:16.17.1-buster](https://hub.docker.com/layers/library/node/16.17.1-buster/images/sha256-674750127bbf45f52660ada71ed1f1491d15e94c16583bff6df0df2489481049?context=explore)

Running tests on the [Karma](https://karma-runner.github.io/latest/index.html) and [Jasmine](https://jasmine.github.io/) frameworks

* building a Dockerfile `docker-build/docker-actions/Dockerfile` in which we install the browser `chrome:latest`
* running unit tests

2024-04-05 15:46 UTC, VitaliySerov requested changes
Looks very good, a great job

Some minor changes 

Also please check the action log:

https://github.com/palladium-tms/palladium-view/actions/runs/8572163899/job/23494065553?pr=430

It shows a lot of errors:
```
ERROR: 'NG0304: 'mat-error' is not a known element:
1. If 'mat-error' is an Angular component, then verify that it is part of this module.
2. If 'mat-error' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
```

but test seems working, better to fix those

2024-04-05 15:46 UTC, VitaliySerov commented on .github/workflows/jasmine.yml
> +      uses: actions/checkout@v2
v4 is the latest

2024-04-05 15:46 UTC, VitaliySerov commented on docker-build/docker-actions/Dockerfile
> +FROM node:16.17.1-buster
Maybe call the dir for it more clear - not `docker-actions` but maybe something `unit-test-runner`

2024-04-05 15:46 UTC, VitaliySerov commented on docker-build/docker-actions/Dockerfile
> +FROM node:16.17.1-buster
Please make sure that this docker is part of dependabot and will be update at same time as default dockerfile

2024-07-24 16:52 UTC, askonev commented
> Looks very good, a great job
> 
> Some minor changes
> 
> Also please check the action log:
> 
> https://github.com/palladium-tms/palladium-view/actions/runs/8572163899/job/23494065553?pr=430
> 
> It shows a lot of errors:
> 
> ```
> ERROR: 'NG0304: 'mat-error' is not a known element:
> 1. If 'mat-error' is an Angular component, then verify that it is part of this module.
> 2. If 'mat-error' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
> ```
> 
> but test seems working, better to fix those

There was an error at startup
```log
(node:19) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /palladium-view/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
```
means that the postcss package is using an outdated way of specifying module exports in its package.json. This is a warning about future compatibility and does not usually affect the functionality of the package immediately but indicates that the package might need an update or configuration change in the future.

2024-07-26 07:31 UTC, VitaliySerov commented on unit-test-runner/Dockerfile
> +CMD ["run", "ng", "test"]
Question - do we really need a separate dockerfile to run unit tests?
Can we do it without docker - just install all deps inside GitHub Actions and run some comments?

I think that way we will be little bit more flexible in future - if we need we can create a dockerfile later
But having this command as native commands will allow us to run unit-tests easily on dev machine while development some feature without a need to constant rebuilding the dockerfile to rerun all the tests

In my option we need Dockerfile only for some production check, but unit-tests can be done on machined/GitHub Action directly

2024-07-26 07:31 UTC, VitaliySerov approved these changes

2024-08-01 18:09 UTC, VitaliySerov approved these changes
Nice job

2024-08-01 19:08 UTC, merged